# Site settings
title: ""
description: ""
baseurl: "/whoami" 
url: "https://nightcrawlerai.github.io"
author_profile: true  # Enable the author profile globally

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Author Information (for the bio widget)
author:
  name: "Ken Jones"
  avatar: "/assets/images/profile.jpg" 
  bio: "Full Stack Data Scientist"
  location: "San Francisco, CA"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/NightCrawlerAI"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/kenrjones1"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:kenrjones@berkeley.edu"

# Defaults (apply layouts and settings globally)
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "home"  # Set default layout for pages to 'home'
      author_profile: true  # Enable the author profile globally
      widgets:
        - about # to show bio/avatar
        - links # to show social links

# Collections (for pages with permalinks)
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: false # Disable posts collection

# Plugins/Extensions
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-gist
  - jekyll-paginate

# Exclusions (ignore these files/directories during build)
exclude:
  - "README.md"
  - "KJ Bio.Rmd"